name: Deploy Cloud Function

on:
  repository_dispatch:
    types:
      - deploy-function

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v1

    - name: Checkout source code
      uses: actions/checkout@v2
      with:
        repository: 'https://github.com/yesaswi/test-serverless-ci'
        path: 'source'

    - name: Initialize Terraform
      run: terraform init

    - name: Validate Terraform configuration
      run: terraform validate

    - name: Plan Terraform changes
      run: terraform plan

    - name: Apply Terraform changes
      run: terraform apply -auto-approve
