name: Destroy Terraform resources

on:
  workflow_dispatch:

jobs:
  terraform-destroy:
    runs-on: ubuntu-latest
    env:
      TF_VAR_region_name: ${{ secrets.GCP_REGION }}
      TF_VAR_project_id: ${{ secrets.GCP_PROJECT_ID }}
      GOOGLE_APPLICATION_CREDENTIALS: sa_key.json

    steps:
    - name: Set up Google Cloud credentials
      run: echo '${{ secrets.GCP_SA_KEY }}' > sa_key.json
    
    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v2

    - name: Initialize Terraform
      run: terraform init

    - name: Create or Select destroy Terraform Workspace
      run: terraform workspace select destroy || terraform workspace new destroy

    - name: Validate Terraform configuration
      run: terraform validate

    - name: Plan Terraform changes
      run: terraform plan

    - name: Destroy Terraform resources
      run: terraform destroy -auto-approve
